#include<stdio.h>
int fact(int n)
{
    if(n<=1)
    {
        return 1;
    }
    else
    {
        return n*fact(n-1);
    }
}
int ncr(int n,int r)
{
    int t1,t2,t3;
    t1=fact(n);
    t2=fact(r);
    t3=fact(n-r);
    return t1/(t2*t3);
}
int  comb(int n,int r)
{
    if(r==0||n==r)
    {
        return 1;
    }
    else
    {
        //this is generated by using pascal's triangle
        return comb(n-1,r-1)+comb(n-1,r);
    }
}
int main()
{
    printf("combination of 7 c 2=%d\n",comb(7,2));
    printf("combination of 7 c 2=%d\n",ncr(7,2));

    return 0;
}